Task - 1: Create a Python program that converts between different units of measurement. • The program should:

1.Prompt the user to choose the type of conversion (e.g., length, weight, volume).

2.Ask the user to input the value to be converted.

3.Perform the conversion and display the result.

4.Handle potential errors, such as invalid input or unsupported conversion types. • Requirements:

5.Functions: Define at least one function to perform the conversion.

6.Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

7.User Input: Prompt the user to select the conversion type and input the value.

8.Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value. • Conversion Options:

9.Length: – Convert meters (m) to feet (ft). – Convert feet (ft) to meters (m).

10.Weight: – Convert kilograms (kg) to pounds (lbs). – Convert pounds (lbs) to kilograms (kg).

11.Volume: – Convert liters (L) to gallons (gal). – Convert gallons (gal) to liters (L).

In [ ]:
def main():
    """
    Function converts user's value to different units based on the conversion type.
    Returns: converted value or an error message if an error occurs.
    """
    try:
        # Prompt the user for the type of conversion
        print("Choose the type of conversion:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")
        conversion_type = int(input("Enter your choice (1, 2, or 3): "))

        # Validate conversion type
        if conversion_type not in [1, 2, 3]:
            raise ValueError("Invalid choice. Please select 1, 2, or 3.")

        # Prompt the user for the value to convert
        conversion_value = float(input("Enter the value for conversion: "))

        # Perform the conversion based on the type
        if conversion_type == 1:
            print("Length Conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            length_choice = int(input("Enter your choice (1 or 2): "))
            if length_choice == 1:
                result = conversion_value * 3.28084
                print(f"{conversion_value} meters = {result:.2f} feet")
            elif length_choice == 2:
                result = conversion_value / 3.28084
                print(f"{conversion_value} feet = {result:.2f} meters")
            else:
                print("Invalid choice for length conversion.")

        elif conversion_type == 2:
            print("Weight Conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            weight_choice = int(input("Enter your choice (1 or 2): "))
            if weight_choice == 1:
                result = conversion_value * 2.20462
                print(f"{conversion_value} kilograms = {result:.2f} pounds")
            elif weight_choice == 2:
                result = conversion_value / 2.20462
                print(f"{conversion_value} pounds = {result:.2f} kilograms")
            else:
                print("Invalid choice for weight conversion.")

        elif conversion_type == 3:
            print("Volume Conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            volume_choice = int(input("Enter your choice (1 or 2): "))
            if volume_choice == 1:
                result = conversion_value * 0.264172
                print(f"{conversion_value} liters = {result:.2f} gallons")
            elif volume_choice == 2:
                result = conversion_value / 0.264172
                print(f"{conversion_value} gallons = {result:.2f} liters")
            else:
                print("Invalid choice for volume conversion.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")


# Call the main function
if __name__ == "__main__":
    main()

Choose the type of conversion:
1. Length
2. Weight
3. Volume
Enter your choice (1, 2, or 3): 1
Enter the value for conversion: 1
Length Conversion:
1. Meters to Feet
2. Feet to Meters
Enter your choice (1 or 2): 2
1.0 feet = 0.30 meters


Create a Python program that performs various mathematical operations on a list of numbers. • The Program should:

1.Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).

2.Ask the user to input a list of numbers (separated by spaces).

3.Perform the selected operation and display the result.

4.Handle potential errors, such as invalid input or empty lists. • Requirements:

5.Functions: Define at least one function for each operation (sum, average, maximum, mini- mum).

6.Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).

7.User Input: Prompt the user to select the operation and input the list of numbers.

8.Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.

In [2]:
def num_list():
  """  ask user to input list of numbers (separated by spaces).
       Returns a list of floating point numbers that users enter
  """
  while True:
        try:
            user_input = input("Enter a list of numbers separated by spaces: ").split()
            if not user_input:
                raise ValueError("Input cannot be empty.")
            num = [float(num) for num in user_input]
            return num
        except ValueError as e:
            print(f"Invalid input: {e}. Please enter numeric values only.")

def calculate_sum(num):
    """
    Calculate the sum of a list of numbers.
    Parameters:
    numbers (list): A list of numeric values.
    Returns:
    float: The sum of the numbers.
    """
    return sum(num)

def calculate_average(num):
    """
    Calculate the average of a list of numbers.
    Parameters:
    numbers (list): A list of numeric values.
    Returns:
    float: The average of the numbers.
    """
    return sum(num) / len(num)

def find_maximum(num):
    """
    Find the maximum value in a list of numbers.
    Parameters:
    numbers (list): A list of numeric values.
    Returns:
    float: The maximum value in the list.
    """
    return max(num)

def find_minimum(num):
    """
    Find the minimum value in a list of numbers.
    Parameters:
    numbers (list): A list of numeric values.
    Returns:
    float: The minimum value in the list.
    """
    return min(num)
def main():
    """
    Main function to run the program.
    """
    print("Welcome to the Math Operations Program!")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    while True:
        try:
            choice = input("Enter your choice (1/2/3/4): ").strip()
            if choice not in ["1", "2", "3", "4"]:
                raise ValueError("Invalid choice. Please select 1, 2, 3, or 4.")

            numbers = num_list()

            if choice == "1":
                result = calculate_sum(numbers)
                print(f"The sum of the numbers is: {result}")
            elif choice == "2":
                result = calculate_average(numbers)
                print(f"The average of the numbers is: {result}")
            elif choice == "3":
                result = find_maximum(numbers)
                print(f"The maximum number is: {result}")
            elif choice == "4":
                result = find_minimum(numbers)
                print(f"The minimum number is: {result}")

            break  # Exit the loop after successful operation
        except ValueError as e:
            print(f"Error: {e}. Please try again.")
        except ZeroDivisionError:
            print("Error: Cannot calculate average of an empty list.")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()

Welcome to the Math Operations Program!
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter a list of numbers separated by spaces: 2 3 5 7
The sum of the numbers is: 17.0


Write a Python function that extracts every other element from a list, starting from the first element. • Requirements: – Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list. – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [8]:
def extract_every_other(lst):
  return lst[::2]
def user_list():
  while True:
        try:
            input_num = input("Enter a list of numbers separated by spaces: ").split()
            numbers = [int(num) for num in input_num]
            if not numbers:
                raise ValueError("list cannot be empty.")
            return numbers
        except ValueError:
            print("Invalid input. Enter only numbers separated by spaces.")


ulist = user_list()
result = extract_every_other(ulist)
print("Every other element:", result)

Enter a list of numbers separated by spaces: 1 2 3 4 5
Every other element: [1, 3, 5]


Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index. • Requirements: – Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive). – Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [9]:
def get_sublist(lst, start, end):
    return lst[start:end + 1]
def user_list():
    while True:
        try:
            user_input = input("Please enter a list of numbers separated by spaces: ").split()
            numbers = [int(num) for num in user_input]
            if not numbers:
                raise ValueError("The list cannot be empty.")
            return numbers
        except ValueError:
            print("Invalid input.Enter only numbers separated by spaces.")

def user_index(prompt, max_index):
    while True:
        try:
            index = int(input(prompt))
            if 0 <= index <= max_index:
                return index
            else:
                print(f"Invalid index.Enter a number between 0 and {max_index}.")
        except ValueError:
            print("Invalid input. Enter a valid integer.")

ulist = user_list()
max_index = len(ulist) - 1
start_index = user_index("Enter starting index: ", max_index)
end_index = user_index("Enter ending index: ", max_index)
if start_index > end_index:
    print("Invalid range. The start index cannot be greater than the end index.")
else:
    result = get_sublist(ulist, start_index, end_index)
    print("Sublist:", result)


Please enter a list of numbers separated by spaces: 2 4 6 9
Enter starting index: 1
Enter ending index: 3
Sublist: [4, 6, 9]


Write a Python function that reverses a list using slicing. • Requirements: – Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing. – Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [11]:
def reverse_list(lst):
  return lst[::-1]
def user_list():
  while True:
    try:
      num_list=input("Please enter numbers list separated by spaces: ").split()
      num=[int(num)for num in num_list]
      if not num:
         raise ValueError("The list cannot be empty.")
      return num
    except ValueError:
            print("Invalid input.Enter only numbers separated by spaces.")


ulist = user_list()
result = reverse_list(ulist)
print("Every other element:", result)


Please enter numbers list separated by spaces: 2 4 6 8 10
Every other element: [10, 8, 6, 4, 2]


Write a Python function that removes the first and last elements of a list and returns the resulting sublist. • Requirements: – Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing. – Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [12]:
def remove_first_last(lst):
    if len(lst) <= 2:
        return []
    return lst[1:-1]

def user_list():
    while True:
        try:
            input_list = input("Please enter list of numbers separated by spaces: ").split()
            numbers = [int(num) for num in input_list]
            if not numbers:
                raise ValueError("The list cannot be empty.")
            return numbers
        except ValueError:
            print("Invalid input.Enter only numbers separated by spaces.")

u_list = user_list()
result = remove_first_last(u_list)
print("list after removing first and last elements:", result)

Please enter list of numbers separated by spaces: 3 6 9 12
list after removing first and last elements: [6, 9]



Write a Python function that extracts the first n elements from a list. • Requirements: – Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing. – Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [13]:
def get_first_n(lst, n):
    return lst[:n]

def user_list():
    while True:
        try:
            input_list = input("Please enter list of numbers separated by spaces: ").split()
            numbers = [int(num) for num in input_list]
            if not numbers:
                raise ValueError("The list cannot be empty.")
            return numbers
        except ValueError:
            print("Invalid input. Enter only numbers separated by spaces.")

u_list = user_list()
n= int(input("Enter the value of n: "))
result = get_first_n(u_list,n)
print("list after extraction:", result)

Please enter list of numbers separated by spaces: 4 8 12 16
Enter the value of n: 2
list after extraction: [4, 8]


Write a Python function that extracts the last n elements of a list using slicing. • Requirements: – Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list. – Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [14]:
def get_first_n(lst, n):
    return lst[:-n]

def user_list():
    while True:
        try:
            input_list = input("Please enter list of numbers separated by spaces: ").split()
            numbers = [int(num) for num in input_list]
            if not numbers:
                raise ValueError("The list cannot be empty.")
            return numbers
        except ValueError:
            print("Invalid input. Enter only numbers separated by spaces.")

u_list = user_list()
n= int(input("Enter the value of n: "))
result = get_first_n(u_list,n)
print("list after extraction:", result)

Please enter list of numbers separated by spaces: 1 2 3 4 5 6 
Enter the value of n: 3
list after extraction: [1, 2, 3]



Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between. • Requirements: – Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward. – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [15]:
def reverse_skip(lst):
    return lst[-2::-2]

def user_list():
    while True:
        try:
            input_list = input("Please enter list of numbers separated by spaces: ").split()
            numbers = [int(num) for num in input_list]
            if not numbers:
                raise ValueError("The list cannot be empty.")
            return numbers
        except ValueError:
            print("Invalid input. Enter only numbers separated by spaces.")

u_list = user_list()
result = reverse_skip(u_list)
print("list after extraction:", result)


Please enter list of numbers separated by spaces: 2 4 6 8 
list after extraction: [6, 2]


1. Flatten a Nested List: Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension. • Requirements: – Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list. – Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [18]:
def flatten(lst):
    flatten_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flatten_list.extend(sublist)
        else:
           flatten_list.append(sublist)
    return flatten_list


nested_list = [[2, 3], [4, 5], [6]]
result = flatten(nested_list)
print(result)

[2, 3, 4, 5, 6]



Write a Python function that extracts a specific element from a nested list given its indices. • Requirements: – Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position. – Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6

In [21]:
def access_nested_element(lst, indices):
    try:
        for index in indices:
            lst = lst[index]
        return lst
    except (IndexError, TypeError):
        return "Invalid indices or structure."

nested_list = [[2, 4, 8], [3, 6, 9], [4, 8, 9]]
indices = [0, 2]
result = access_nested_element(nested_list, indices)
print(result)

8



Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth). • Requirements: – Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements. – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [22]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        elif isinstance(item, (int, float)):
            total += item
    return total


nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)

21


Write a Python function that removes all occurrences of a specific element from a nested list. • Requirements: – Define a function remove element(lst, elem) that removes elem from lst and returns the modified list. – Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [27]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            cleaned_sublist = remove_element(item, elem)
            if cleaned_sublist:
                result.append(cleaned_sublist)
        elif item != elem:
            result.append(item)
    return result
lst = [1, 2, [3, 4, [5, 2]], 2, [6, 2]]
elem = 2  # Element to remove

new_lst = remove_element(lst, elem)
print("Original list:", lst)
print("New list after removing", elem, ":", new_lst)

Original list: [1, 2, [3, 4, [5, 2]], 2, [6, 2]]
New list after removing 2 : [1, [3, 4, [5]], [6]]


Write a Python function that finds the maximum element in a nested list (regardless of depth). • Requirements: – Define a function find max(lst) that takes a nested list lst and returns the maximum element. – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [29]:
def find_max(lst):
    max_value = 0

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        elif isinstance(item, (int, float)):
            max_value = max(max_value, item)

    return max_value


nested_list = [[2, 4], [3, [9, 27]], 12]
result = find_max(nested_list)
print(result)

27



Write a Python function that counts how many times a specific element appears in a nested list. • Requirements: – Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst. – Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [32]:

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


nested_list = [[3, 2], [2, 3], [4, 3]]
elemcount = 4
result = count_occurrences(nested_list, elemcount)
print(result)

1


Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth. • Requirements: – Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list. – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [33]:
def deep_flatten(lst):
    flattened = []

    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)

    return flattened

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


Write a Python function that calculates the average of all elements in a nested list. • Requirements: – Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements. – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [36]:
def average_nested(lst):
    def flatten(nested_lst):
        flat_list = []
        for item in nested_lst:
            if isinstance(item, list):
                flat_list.extend(flatten(item))
            else:
                flat_list.append(item)
        return flat_list

    flat_list = flatten(lst)
    if not flat_list:
        raise ValueError("The input list is empty.")
    return sum(flat_list) / len(flat_list)

nested_list = [[4, 8], [5, 10], [6, 12]]
average = average_nested(nested_list)
print("Average of all elements in the nested list:", average)

Average of all elements in the nested list: 7.5


10.1 Basic Vector and Matrix Operation with Numpy. Problem - 1: Array Creation: Complete the following Tasks:

1.Initialize an empty array with size 2X2.

2.Initialize an all one array with size 4X2.

3.Return a new array of given shape and type, filled with fill value.{Hint: np.full}

4.Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

5.Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [37]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty array with size (2x2):\n", empty_array)

ones_array = np.ones((4, 2))
print("All ones array with size (4x2):\n", ones_array)

fill_value_array = np.full((3, 3), 7)
print("Array filled with 7 (3x3):\n", fill_value_array)

reference_array = np.array([[4, 5, 6], [7, 8, 9]])
zeros_like_array = np.zeros_like(reference_array)
print("Zeros array with same shape as reference array:\n", zeros_like_array)

ones_like_array = np.ones_like(reference_array)
print("Ones array with same shape as reference array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted numPy array from list:\n", numpy_array)

Empty array with size (2x2):
 [[4.27666079e-316 0.00000000e+000]
 [6.19654689e-091 1.08601666e-071]]
All ones array with size (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros array with same shape as reference array:
 [[0 0 0]
 [0 0 0]]
Ones array with same shape as reference array:
 [[1 1 1]
 [1 1 1]]
Converted numPy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing: Complete the following tasks:

1.Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

2.Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

3.Create a 3X3 identity matrix.{Hint:np.eye()}

4.Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}

5.Create a 10X10 array with random values and find the minimum and maximum values.

6.Create a zero array of size 10 and replace 5th element with 1.

7.Reverse an array arr = [1,2,0,0,4,0].

8.Create a 2d array with 1 on border and 0 inside.

9.Create a 8X8 matrix and fill it with a checkerboard pattern.

In [38]:
array_10_to_49 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", array_10_to_49)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0 to 8):\n", matrix_3x3)

identity_matrix = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array mean:\n", mean_value)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. Min & Max of 10x10 array:\nMin:", min_value, "Max:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with border 1 and inside 0:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", checkerboard)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array mean:
 0.4377995440705894

5. Min & Max of 10x10 array:
Min: 0.007867335626629113 Max: 0.9988082468846812

6. Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. 2D array with border 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


For the following arrays: x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]); v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:

1.Add the two array.

2.Subtract the two array.

3.Multiply the array with any integers of your choice.

4.Find the square of each element of the array.

5.Find the dot product between: v(and)w ; x(and)v ; x(and)y.

6.Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

7.Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [40]:

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("1. Addition :\n", add_xy)

sub_xy = x - y
print("\n2. Subtraction:\n", sub_xy)

mul_x = x * 3
print("\n3. Multiplication by 3:\n", mul_x)

square_x = np.square(x)
print("\n4. Square of each element :\n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot Product Results:")
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

concat_xy = np.concatenate((x, y), axis=0)
print("\n6. Concatenation of x and y along rows:\n", concat_xy)

concat_vw = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. Error when concatenating x and v:\n", e)

1. Addition :
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. Multiplication by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element :
 [[ 1  4]
 [ 9 25]]

5. Dot Product Results:
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

7. Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


• For the following arrays: A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:

1.Prove A.A−1 = I.

2.Prove AB ̸= BA.

3.Prove (AB)T = BT AT

4.Solve the following system of Linear equation using Inverse Methods. 2x−3y + z =−1 x−y + 2z =−3 3x + y−z = 9 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX= B} • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func- tion of Numpy}

In [41]:
A = np.array([[3, 4], [7, 8]])

A_inv = np.linalg.inv(A)

A_Ainv = np.dot(A, A_inv)


print("1. A * A_inv = Identity Matrix:")
print(A_Ainv)

1. A * A_inv = Identity Matrix:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [42]:
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("\nBA =\n", BA)
print("\nAB == BA:", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

AB == BA: False


In [43]:
AB_T = np.transpose(AB)

A_T = np.transpose(A)
B_T = np.transpose(B)

BT_AT = np.dot(B_T, A_T)

print("(AB)_t:\n", AB_T)
print("\n(B_t * A_t):\n", BT_AT)
print("\n(AB)_t == (B_t * A_t):", np.allclose(AB_T, BT_AT))

(AB)_t:
 [[23 51]
 [13 29]]

(B_t * A_t):
 [[23 51]
 [13 29]]

(AB)_t == (B_t * A_t): True


In [44]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv=np.linalg.inv(A)
X=np.dot(A_inv,B)
print("Solution for [x,y,z]:",X)


Solution for [x,y,z]: [ 2.  1. -2.]
